language: cpp
dist: trusty
sudo: required
group: deprecated-2017Q4

compiler:
  - gcc
matrix:
  include:
    # build on ubuntu
    - os: linux
      sudo: required
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9 libasound2-dev libvorbisidec-dev libvorbis-dev libflac-dev alsa-utils libavahi-client-dev avahi-daemon
    # build on osx
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="brew update && brew install flac libvorbis"
  allow_failures:
    - os: osx
before_install:
    - eval "${MATRIX_EVAL}"
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then BUILD_PARAMS="TARGET=MACOS"          ; fi
  - make $BUILD_PARAMS
  - sudo make installclient $BUILD_PARAMS
  - sudo make installserver $BUILD_PARAMS
